  
name: build latest node
on:
  push:
    branches:
      - main
    paths:
      - Node-Latest/**

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push:
    name: 'Node-Latest:${{ matrix.Node-Latest }}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        Node-Latest:
          - node

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          version: 'v0.5.1'
          buildkitd-flags: --debug

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker/GHCR
      # https://github.com/docker/metadata-action
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - uses: docker/build-push-action@v2
        with:
          context: ./Node-Latest/${{ matrix.Node-Latest }}
          file: ./Node-Latest/${{ matrix.Node-Latest }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/M1DN1GHT01/Node-Latest:${{ matrix.Node-Latest }}
